export function mapPagarmeError(acquirerCode: string | null | undefined): string {
  const map: Record<string, string> = {
    '1000': 'Pagamento não aprovado. Tente outro cartão.',
    '1001': 'Cartão vencido. Verifique a data de validade.',
    '1002': 'Transação recusada por suspeita de fraude.',
    '1004': 'Cartão com restrição. Entre em contato com seu banco.',
    '1011': 'Número do cartão inválido.',
    '1016': 'Saldo insuficiente.',
    '1017': 'Senha inválida.',
    '1019': 'Transação não permitida para este cartão.',
    '1021': 'Limite do cartão excedido.',
    '1025': 'Cartão bloqueado. Entre em contato com seu banco.',
    '1032': 'Cartão cancelado (perdido ou roubado).',
    '1045': 'Código de segurança inválido. Verifique o CVV.',
    '2000': 'Pagamento não aprovado. Tente outro cartão.',
    '2001': 'Cartão vencido. Verifique a data de validade.',
    '2002': 'Transação recusada por suspeita de fraude.',
    '2004': 'Cartão com restrição. Entre em contato com seu banco.',
    '2008': 'Cartão cancelado (reportado como perdido).',
    '2009': 'Cartão cancelado (reportado como roubado).',
    '05': 'Pagamento não autorizado. Entre em contato com seu banco.',
    '14': 'Número do cartão inválido.',
    '25': 'Cartão bloqueado. Entre em contato com seu banco.',
    '41': 'Cartão bloqueado. Reportado como perdido.',
    '43': 'Cartão bloqueado. Reportado como roubado.',
    '51': 'Saldo insuficiente.',
    '54': 'Cartão vencido. Verifique a data de validade.',
    '55': 'Senha incorreta.',
    '57': 'Transação não permitida para este cartão.',
    '62': 'Código de segurança inválido. Verifique o CVV.',
    '63': 'Código de segurança inválido. Verifique o CVV.',
    '65': 'Limite de transações excedido.',
    '75': 'Número de tentativas de senha excedido. Contate seu banco.',
    '78': 'Cartão bloqueado. Entre em contato com seu banco.',
    '82': 'Código de segurança inválido. Verifique o CVV.',
    '91': 'Banco emissor indisponível. Tente novamente em instantes.',
    '96': 'Erro no sistema. Tente novamente.',
  }
  return map[acquirerCode ?? '']
    ?? 'Pagamento recusado. Tente novamente ou use outro cartão.'
}
